### PR TITLE
Add display of dispatched actions and their payload

### PR DESCRIPTION
**Pull request by codeheroics**
Hi, Thanks for the amazing work on this!

This is a proposal to get a display of dispatched actions. Currently, we can see the diff and state for each action, but not the payload of the action, which could be quite helpful.

The current demo did not really show why someone would need to this display as none of the fired actions had anything but a type, so I added a button able to fire an action fired with a random payload.

### CODE REVIEW

**Comment by alexkuz** [comment]
Thank you!

I'll check it out a bit later.

**Comment by alexkuz** [comment]
I think `Action` tab should have its own `inspectedPath`, as the payload is not correlated with the state. Otherwise seems fine!

**Comment by codeheroics** [comment]
I just updated the PR to provide a different `inspectedPath` depending on whether or not the user is on the Action tab, tell me what you think about it!

**Comment by alexkuz** [comment]
Great, thank you!

**Pull request merged**
