### PR TITLE
Select start and end point for the Diff

### PR DESCRIPTION
**Pull request by zalmoxisus**
It allows comparing not only 2 consecutive actions, but also by an interval:

znamgskj64

Just hold `Shift` key when clicking.

### CODE REVIEW

**Comment by alexkuz** [comment]
Thank you! I'll try it later - meanwhile, I've added you as collaborator (on npm as well)

**Comment by alexkuz** [comment]
@zalmoxisus sorry for delay, just took a look.
I've found that interval selection is working, only if the first action is also selected with `Shift` pressed. Is it by design? Usually, it doesn't work like this - you can select first action as usual, and then select interval with `Shift`. Not a big issue, but I find it more intuitive.

**Comment by zalmoxisus** [comment]
Agree. I'll change that.

**Comment by zalmoxisus** [comment]
Updated.

[Here](https://youtu.be/cbXLohVbzNI?t=392) I present this feature, and also the ability to generate tests for the selected interval of actions. The only problem is that I use `codemirror` to format the generated code, which requires adding global style for `CodeMirror` class. Any ideas how we could implement that? Anyway, it should be in a separate PR.

**Comment by alexkuz** [comment]
Wow, cool!

Test generation is very interesting, but I'm not sure if it should be in this repo. Maybe we should support plugins that will provide custom tabs?

**Comment by zalmoxisus** [comment]
Yes, having custom tabs would be great. That would also allow using `codemirror` styles externally if needed.

Something like:

``` jsx
<InspectorMonitor {...{
   shouldPersistState: false,
   customTabs: {
      'Test': <TestGenerator />
   }
}} />
```

**Pull request merged**
